### ISSUE TITLE
2023-10-17 双周会内容

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#162]
主题：Serverless 社区双周会
时间：10月17日 周二 19:30 - 20:30 （GMT +8:00）

会议号：
90957500367

入会链接：
https://meeting.dingtalk.com/j/N2PVaS6amy8

#### SOFAServerless
- [x] 官网搭建  https://sofaserverless.netlify.app/ 

#### ModuleController
- [x] 修复 ModuleController 使用 Arklet 遇到的问题 https://github.com/sofastack/sofa-serverless/issues/17
- [x] [先扩后缩](https://github.com/sofastack/sofa-serverless/issues/62)
- [ ] 单测达到 80/60、8+ 集成测试、CI 自动化、快速开始 #72 #73   。还差集成测试，当前只实现了 1 个发布主链路，更多用例正在[开发中](https://github.com/sofastack/sofa-serverless/issues/167)。
- [x] ModuleController 各项参数校验
- [x] [replicas = -1 表示对等架构 #94](https://github.com/sofastack/sofa-serverless/issues/94)  ，对等架构本周会重新完成详细设计、接口和代码脚手架搭建，在[另一个 Issue](https://github.com/sofastack/sofa-serverless/issues/165)跟进。
- [x] 发布的分组策略，扩缩容的分组策略 
- [x] 模块流量 https://github.com/sofastack/sofa-serverless/issues/64  。正在开发，本周上线。

#### 研发框架
- [x] [服务的跨SpringContext 发现与调用](https://github.com/sofastack/sofa-serverless/issues/67) 
- [x] [FEATURE] 关于 arklet 健康检查解决方案 #25
- [x] 模块安装支持远程协议
- [x] [【spring-boot-ark-plugin】 #74](https://github.com/sofastack/sofa-serverless/issues/74)
- [x] [【Arklet】指令耗时统计和资源消耗统计设计 #77](https://github.com/sofastack/sofa-serverless/issues/77)
- [x] 3个中间件评测，samples 样例库统一维护至[这里](https://github.com/sofastack/sofa-serverless/tree/master/samples) 
- [x] 健康状态检查方案 review
- [x] 基座引用的 starter，支持 Spring Boot、SOFABoot，Arklet 版本推到 Maven 中央仓库 
- [x] 基座 Starter，Arklet 0.3 版本打包发版 
- [x] [基座模块1:1 复用 ClassLoader](https://github.com/sofastack/sofa-ark/issues/710), 结论不可行
- [x] 增加锁控制 https://github.com/sofastack/sofa-serverless/issues/39

## SpringBoot 一键转为模块端到端演示
@hustchaya 
1. 一套代码分支可独立启动，也可构建为模块启动。
2. 模块可自动瘦身，并能启动成功。

#### SOFAServerless
设计文档与 RoadMap 需要补充，以后每个双周会纪要贴在这里
|isseus| Owner | 进度 |备注|
|-|-|-|-|
| KCD, 云栖大会，12 月QCon 准备 | @lvjing2  | | |
| 数马分享 | @yuanyuan2021 @gold300jin  | | |
| 录制完成的从开发到上线，流量调用的完整视频，后续发布到官网和后续运营交流 | @lvjing2 | | |

#### Arklet & Runtime
设计文档与 RoadMap 需要补充，以后每个双周会纪要贴在这里
|isseus| Owner | 进度 |备注|
|-|-|-|-|
|jdk 17, springboot 3.x https://github.com/sofastack/sofa-serverless/issues/151| @hustchaya  | | |
|支持中间件列表与优先级，排摸支持情况，设计评测标准 | @lvjing2 | 未开始 | |
|服务调用优化、samples与文档 https://github.com/sofastack/sofa-serverless/issues/149| @yuanyuan2021  | ||
| 灵活部署 https://github.com/sofastack/sofa-serverless/issues/160 | @hustchaya  | | |
| 中间件统一强制委托与模块瘦身方案设计与实现 https://github.com/sofastack/sofa-serverless/issues/148| @hustchaya  | | |
| installBiz 接口不需要传 bizName、bizVersion，改成从jar包里提取 #147 https://github.com/sofastack/sofa-serverless/issues/147 | @sususama  | | |
| queryAllBiz 返回信息不包含基座部分 #146 https://github.com/sofastack/sofa-serverless/issues/146 | @sususama  | | | 
| sofaserverless 单测数据恢复 https://github.com/sofastack/sofa-serverless/issues/113 | @all | | |
| spring-boot 的多模块运行环境原理解析文档整理 https://github.com/sofastack/sofa-serverless/issues/127 | @yuanyuan2021  | | |
| 设置默认启动参数，https://github.com/sofastack/sofa-serverless/issues/123 | @yuanyuan2021  | | |
| dubbo 框架支持 https://github.com/sofastack/sofa-serverless/issues/140 | @zjulbj  | | | 
| 官方文档更新 #174 | @lvjing2  | | |

#### SOFAArk 
|isseus| Owner | 进度 |备注|
|-|-|-|-|
[support apollo config for issue #601](https://github.com/sofastack/sofa-ark/pull/744) | @zhushikun | | |
| [支持 SOFABoot 4 和 JDK 17](https://github.com/sofastack/sofa-ark/issues/704) | @yuanyuan2021  | | |
| skywalking-agent 和 sofa ark 兼容问题 https://github.com/sofastack/sofa-ark/issues/703| | | |
| https://github.com/sofastack/sofa-ark/issues/730 | @TomorJM  | | |

#### Arkctl 
设计文档与 RoadMap 需要补充，以后每个双周会纪要贴在这里
|isseus| owner | 进度 |备注|
|-|-|-|-|
| Arkctl 增加模块代码脚手架初始化能力 #83| 待认领 | | |

#### ModuleController
设计文档与 RoadMap 需要开放出来，以后每个双周会纪要贴在这里
|isseus| Owner | 进度 |备注|
|-|-|-|-|
| [重启更新](https://github.com/sofastack/sofa-serverless/issues/158) | @liu-657667   | ||
| [对等模式详细设计、接口和代码脚手架搭建](https://github.com/sofastack/sofa-serverless/issues/165) | @gold300jin | ||
| [新增 2+ 端到端用例](https://github.com/sofastack/sofa-serverless/issues/167) | @zemingzhu | ||

Arkctl Arklet ModuleController 0.6 发版本

**Comment by lvjing2** [comment]
### 关于模块瘦身的几个考虑 @hustchaya @yuanyuan2021 
1. url 和 文件的 exclude 的排他性？当前采用取并集的方式，暂不考虑排他性
2. 多个模块的升级问题？如果平台名单列表或基座名单列表修改，导致模块升级失败的问题，如何处理？
3. 黑盒性？模块开发者感知不到实际使用的依赖是什么版本，与代码里写的实际不同，存在一定的困扰，是否配合 arkctl 或运行诊断能力？
