### ISSUE TITLE
[Feature] Operator 支持多种 Module 部署策略

### ISSUE THREAD

**Issue by Charlie17Li** [sofastack/sofa-serverless#21]
## In what area(s)?
/area operator

### 背景

实际生产上部署或者升级 Module 往往需要十分谨慎，我们需要一定的部署策略来降低变更带来的风险，需要做到`可灰度;可监控;可回滚`

### 需求

- [ ] 自定义分组策略: 该策略将 Module 部署分成多个组顺序执行 #22 
- [ ] Beta 确认策略:    该策略在部署时会先尝试部署一个 Module 经过人工观察确认后，方可执行后续部署流程
- [ ] 分组确认策略:     该策略执行需要开启自定义分组策略，在每个分组部署后需要人工观察确认后，方可进行后续分组部署 #33 
- [ ] 灰度时间策略：该策略执行需要开启自定义分组策略，在每个分组部署后需要等待设置的灰度时间，如果 Module 状态正常方可进行后续分组部署 #33 
- [ ] 最大不可用数量策略：TODO

在同一个分组中，Module 部署到 Pod 上有两种选择方式
- [x] 分组 Pod 选择策略,打散: 将 Module 尽可能放置到空闲的 Pod 上 #45 
- [x] 分组 Pod 选择策略,堆叠：将 Module 尽可能放置到非空闲的 Pod 上 #45 

#### ModuleDeployment
ModuleDeployment 通过控制 ModuleReplicaSet 来实现: beta部署、分批部署、分组确认、灰度时间等部署策略，对于一个ModuleDeployment CR 其协调过程具体如下:
1. 检查是否需要需要创建新批次
    1. 如果所有批次都发布完成就返回
    2. 如果存在下一个批次就创建新批次
2. 检查是否开启 beta部署策略
    1. 若开启则更新 ModuleReplicaSet 其replica 为 1
    2. 若没有开启，则进入正常批次流程 
2. 正常批次流程下，计算当前批次期望的 replica 值，然后更新 ModuleReplicaSet
3. 更新 ModuleReplicaSet 后，则首先判断是否开启**分组确认**策略
    1. 若开启，则修改 ModuleDeployment.Spec.Pause 进入暂停，等待用户确认
4. 其次判断**灰度时间**策略是否开启
    1. 若开启，则修改 ModuleDeployment.Spec.Pause 进入暂停，并创建一个延时任务加入本地延时队列，规定时间后再 Resume
5. 最后判断当前批次是否是最后一批
    1. 如果不是，则进入重新更新 ModuleReplicaSet
    2. 否则结束 Reconcile

<div align="center">
<img width="456" alt="image" src="https://github.com/sofastack/sofa-serverless/assets/32014420/a0bcf381-b60a-45e7-946b-99dc4a1c2a74">
</div>

#### ModuleReplicaSet
ModuleReplicaSet 主要负责协调同分组之内的 Module 部署，在 Reconcile 方法中，对于一个 moduleReplicaSet 资源：
1. 首先检查是否开启 `MaxUnvaliable` 策略，若开启则检查是否满足最大不可用数
2. 其次根据 `Module` 的部署类型执行不同的分组策略: 打散、堆叠
<div align="center">
<img width="462" alt="image" src="https://github.com/sofastack/sofa-serverless/assets/32014420/66f0d4b3-4ba5-46a1-9302-b98569fd359c">
</div>

##### 打散 | 堆叠 策略
在 ModuleReplicaSet Controller 为每个Module选择 Pod时，首先从 APIServer 根据 deployment 获取一组 Pod， 并根据策略(打散|堆叠)对 pod 进行打分排序，最后执行 Module 绑定
<div align="center">
<img width="801" alt="image" src="https://github.com/sofastack/sofa-serverless/assets/32014420/1c488a60-e0ea-4a2a-93fb-abd1cbb1fc4f">
</div>

- 当采用打散策略时，优先选择使用 Biz 模块数少的 Pod
- 当采用堆叠策略时，优先选择使用 Biz 模块数多的 Pod，并且 Biz模块数量没有超过设定的阈值

**Comment by lylingzhen** [comment]
@Charlie17Li 这个 PR 合并后，需要补充一个面向用户视角如何配置模块发布运维策略的文档。说明清楚 beta 部署、分批部署、分组确认、灰度时间等部署策略如何配置和使用。

**Comment by lylingzhen** [comment]
0.5 版本和文档已发布，close。
