### ISSUE TITLE
2023-11-28 双周会内容

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#335]
主题：Serverless 社区双周会
时间：11月28日 周二 19:30 - 20:30 （GMT +8:00）

会议号：
90957500367

入会链接：
https://meeting.dingtalk.com/j/NcviAc6j6dM

### SOFAServerless 新增2分钟上手 demo 视频
1. 后续企业支持，新问题发现  @all
2. 开源中间件治理 @TomorJM  待确定中间件 nacos
3. 更多 samples 用例验证 https://github.com/sofastack/sofa-serverless/issues/232 
4. 跟进或分配现有待 review 的PR

### Runtime & Arklet
迭代规划 @yuanyuancin @TomorJM 

- [x] jdk 17, springboot 3.x @hustchaya , 测试完成，打出版本，单测，打包问题 @lvjing2 
- [x]  dubbo 2.0 合并部署支持、包含 rpc filter @zjulbj , 2.6 已支持 , 2.7 改造中在另外 issue 跟进
- [x]  [适配 Apollo and Jasypt](https://github.com/sofastack/sofa-serverless/pull/217)  @it-linnan  待review
- [x] ehcache 冲突 #228   @qixiaobo @lvjing2 
- [x]  模块与 springboot 构建产物重复 #221   @hustchaya  
- [x]  支持 springboot1.x #222  @qixiaobo
- [x] 未指定 declaredMode 导致委托给基座的资源未加载到 #223  @lvjing2 
- [x] 最佳实践，支持的中间件列表 #224  @lvjing2 
9. ClassLoaderHook 文档 #225  @glmapper 
10. 服务动态代理 @yuanyuancin 
- [x] apollo 不同 biz 冲突 #226  @qixiaobo 
12. Runtime 自身组件依赖与用户依赖相互影响 #227   @yuanyuancin 
- [x] 低成本的多应用合并治理sdk接入方案 #229  @lvjing2 
15. 多应用问题扫描与治理 #230  @CodeNoobKing  开始调研，包括引入的jar，甚至 java agent

### ModuleController 
迭代规划 @gold300jin 

1.  最大不可用数量 @Charlie17Li   开发review中 
- [x]  下线分批 @Charlie17Li 
- [x]  核心链路所有端到端测试用例，10 条 @liu-657667  @zemingzhu ，已经完成多少条？
5.  ~~对等链路，模块发布~~ @zemingzhu    往后挪
6. 支持 helm 方式部署 moduleController  https://github.com/sofastack/sofa-serverless/issues/219 

### SOFAArk 
迭代规划 @lvjing2 
- [x] 静态合并部署方案优化  @CodeNoobKing  设计中
2. review 代码&方案 @glmapper 
3. CI 覆盖率统计 @glmapper 
4. 事件机制优化 https://github.com/sofastack/sofa-ark/issues/753 @yuanyuancin 补充需要考虑的问题 ，主站内外文档
5. plugin 默认导出自身类 https://github.com/sofastack/sofa-ark/issues/737  @sususama @compasty
6. spring webflux 支持 单 host 多 context 模式

### Arkctl
1. Arkctl 增加模块代码脚手架初始化能力 #83 
2. [ ] 模块脚手架搭建  @sususama,  差文档、发布工作 
- [x] 单测流水线 
- [x] 集成测试，发布版本环境构建 #289 
- [x] 模块构建与部署验证  @CodeNoobKing 0.1 版本已经发布，需要重新构建 @CodeNoobKing 

### 质量建设 @宫九
- [x] 基础验证能力，从用户侧使用角度 
- [ ] 卸载，arkctl 版本变更，流量验证

### Arklet && Runtime
迭代规划 @yuanyuancin @TomorJM 
1. [优化自动排包的配置方式 #330](https://github.com/sofastack/sofa-serverless/issues/330)
2. [支持模块 compile 引入 spring 框架依赖 #329](https://github.com/sofastack/sofa-serverless/issues/329)  @yuanyuancin 
3. [ClassLoader 新增 CNF 缓存能力，参考主站实现，大幅加速应用启动。 #331](https://github.com/sofastack/sofa-serverless/issues/331)
4. [模块安装支持不传递bizName、bizVersion #325](https://github.com/sofastack/sofa-serverless/issues/325) @TomorJM 
5. [基座配置 web context path，模块未配置时无法安装模块 #320](https://github.com/sofastack/sofa-serverless/issues/320)
7. 服务代理，支持 SOFARPC, SpringMVC [支持 SpringMVC 多 ClassLoader 服务调用拦截 #283](https://github.com/sofastack/sofa-serverless/issues/283)  [支持 SOFARPC 跨 ClassLoader 服务路由能力 #268](https://github.com/sofastack/sofa-serverless/issues/268)
8. [支持sofa-serverless-adapter-logback #274](https://github.com/sofastack/sofa-serverless/issues/274)
9. [Arklet 排障性增强 #263](https://github.com/sofastack/sofa-serverless/issues/263) @TomorJM 
10. [支持导出基座依赖的pom方便模块瘦身 #254](https://github.com/sofastack/sofa-serverless/issues/254)
11. [多应用问题的扫描与治理 #230](https://github.com/sofastack/sofa-serverless/issues/230) 
12. dubbo 2.6 samples 小修复，dubbo 2.7
13. dubbo 3.x 补充 samples case

### ModuleController 
迭代规划 @gold300jin 

1. 最大不可用数量 @Charlie17Li   开发review中 
2. 补充新增链路端到端测试用例  @liu-657667  @zemingzhu 
3. 支持 helm 方式部署 moduleController  https://github.com/sofastack/sofa-serverless/issues/219 

### SOFAArk
迭代规划 @lvjing2  
1. [修复 jdk 17 单测 #780](https://github.com/sofastack/sofa-ark/issues/780)
2. [plugin需要默认导出自己的包 #737](https://github.com/sofastack/sofa-ark/issues/737)
14. [事件处理机制，一个模块的一次事件会发送给jvm内所有模块的 handler 处理，导致非预期行为 #753](https://github.com/sofastack/sofa-ark/issues/753)
15. [组件漏洞 #732](https://github.com/sofastack/sofa-ark/issues/732)
16. [文件路径包含空格无法启动项目工程 #724](https://github.com/sofastack/sofa-ark/issues/724)

### Arkctl
迭代规划 @CodeNoobKing 
1. Arkctl 增加模块代码脚手架初始化能力 #83 
2. [ ] 模块脚手架搭建  @sususama,  差文档、发布工作 

### 质量建设
迭代规划 @gongjiu 
- [ ] 继续验证完善

**Comment by sususama** [comment]
#83 文档done
