### ISSUE TITLE
2023-12-26 双周会内容

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#415]
主题：Serverless 社区双周会
时间：12月26日 周二 19:30 - 20:30 （GMT +8:00）

会议号：
90957500367

入会链接：
https://meeting.dingtalk.com/j/3mXRxogBsio

### 12月业务接入进展
3/5 家企业已接入生产，2家企业完成 poc 待发布线上。阿里妈妈、阿里健康、工商银行、政采云、快手、平安财产保险等正在 POC 或开发接入中。

### Arklet && Runtime
迭代规划 @yuanyuancin @TomorJM 
1. [优化自动排包的配置方式 #330](https://github.com/sofastack/sofa-serverless/issues/330) @yuanyuancin 
2. [支持模块 compile 引入 spring 框架依赖 #329](https://github.com/sofastack/sofa-serverless/issues/329)  @yuanyuancin 
3. [ClassLoader 新增 CNF 缓存能力，参考主站实现，大幅加速应用启动。 #331](https://github.com/sofastack/sofa-serverless/issues/331) @zjulbj 
- [x] [模块安装支持不传递bizName、bizVersion #325](https://github.com/sofastack/sofa-serverless/issues/325) @TomorJM 
5. [基座配置 web context path，模块未配置时无法安装模块 #320](https://github.com/sofastack/sofa-serverless/issues/320)
7. 服务代理，支持 SOFARPC, SpringMVC [支持 SpringMVC 多 ClassLoader 服务调用拦截 #283](https://github.com/sofastack/sofa-serverless/issues/283)  [支持 SOFARPC 跨 ClassLoader 服务路由能力 #268](https://github.com/sofastack/sofa-serverless/issues/268)  Kafka, RocketMQ 
- [x] [支持sofa-serverless-adapter-logback #274](https://github.com/sofastack/sofa-serverless/issues/274)
9. [Arklet 排障性增强 #263](https://github.com/sofastack/sofa-serverless/issues/263) @TomorJM 
10. [多应用问题的扫描与治理 #230](https://github.com/sofastack/sofa-serverless/issues/230)  @CodeNoobKing 
11. spring service finder 延迟寻址 @yuanyuancin 
- [x] dubbo 2.6 samples 小修复
- [x] dubbo 2.6 adapter 增加 README.md， 介绍原理，具体修改哪些 @qixiaobo 
12. dubbo 2.7 @zjulbj 
13. dubbo 3.x 补充 samples case @zjulbj 
- [x] 适配 nacos @TomorJM 
- 模块需要 compile 依赖 promothues @CodeNoobKing 
- [x] 适配 spring cloud gateway  @lvjing2 

### ModuleController 
迭代规划 @gold300jin 

1. 最大不可用数量 @liu-657667   开发review中 
- [x] 补充新增链路端到端测试用例  @liu-657667  @zemingzhu 
3. 对等部署 @zemingzhu 
4. usebeta和batchCount的冲突问题 #392 @liu-657667 
5. confirm确认显式指定分批数，保证幂等 #391 @liu-657667 
6. 支持 helm 方式部署 moduleController  https://github.com/sofastack/sofa-serverless/issues/219 

### SOFAArk
迭代规划 @lvjing2  
- [x] [修复 jdk 17 单测 #780](https://github.com/sofastack/sofa-ark/issues/780)
- [x] [plugin需要默认导出自己的包 #737](https://github.com/sofastack/sofa-ark/issues/737)
- [x] [事件处理机制，一个模块的一次事件会发送给jvm内所有模块的 handler 处理，导致非预期行为 #753](https://github.com/sofastack/sofa-ark/issues/753)
- [x] [组件漏洞 #732](https://github.com/sofastack/sofa-ark/issues/732)
- [x] [文件路径包含空格无法启动项目工程 #724](https://github.com/sofastack/sofa-ark/issues/724)
- [x] ClassLoaderHook 待提交 @glmapper 

### Arkctl
迭代规划 @CodeNoobKing 
1. Arkctl 增加模块代码脚手架初始化能力 #83 
2. [ ] 模块脚手架搭建  @sususama,  差文档、发布工作

### 质量建设
迭代规划 @gongjiu 
- [ ] 继续验证完善

**Comment by lvjing2** [comment]
### 针对 dubbo 2.6 2.7 支持相同接口多个服务的成本过高，改为沉淀最佳实践文档
dubbo 2.6 2.7 的中台模式，相同接口发出多个服务。需要把接口通信类统一放在基座上，模块上委托给基座。

### ClassLoader 的扫描
1. Caller ClassLoader 的扫描
2. 返回值是 ClassLoader 的方法，Thread.currentThread().getContextClassLoader() 的调用

### 考虑增加类似 dubbo 的服务模型
1. 维护服务与 ClassLoader 的关系缓存
